import localFont from "next/font/local";
import "./globals.css";

import { cn } from "@/lib/utils";
import { SideBar } from "@/components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          geistSans.className
        )}
      >
        <SideBar />
        {children}
      </body>
    </html>
  );
}
